### ISSUE TITLE
No data for Iskraemeco AM550

### ISSUE THREAD

**Issue by mainzelM** [scs/smartmeter-datacollector#35]
I setup the smartmeter-datacollector using the provided raspberry Pi image. I added both sinks, but there is no data in grafana or in the log:
```
root@raspberrypi:/var/log# journalctl -u DataLogger
-- Logs begin at Wed 2022-08-31 13:14:13 CEST, end at Wed 2022-08-31 14:00:04 CEST. --
-- No entries --
```
When I start the collector from the command line, there is a little bit more to see:
```
root@raspberrypi:/home/pi# /usr/bin/python3 /usr/bin/smartmeter-datacollector -c /var/lib/smartmeter-datacollector/datacollector.ini -d
DEBUG:asyncio:Using selector: EpollSelector
INFO:smartmeter:Successfully set up Iskra AM550 smart meter on '/dev/ttyUSB0'.
DEBUG:asyncio:poll took 0.958 ms: 1 events
INFO:sink:Connected to MQTT broker.
INFO:asyncio:poll 999.539 ms took 1001.060 ms: timeout
INFO:asyncio:poll 999.804 ms took 1001.072 ms: timeout
INFO:asyncio:poll 999.537 ms took 1001.080 ms: timeout
...
```

My smartmeter is an Iskraemeco AM550 operated by the EKZ.

How can I debug this?

**Comment by raymar9** [comment]
Hi mainzelM
You don't see the log with `journalctl` because the unit-name `DataLogger` of the service is wrong. Use `journalctl -u python3-smartmeter-datacollector` instead.

It seems that no serial data arrive at the Raspberry Pi. This can have multiple reasons. I would start with a simple serial reader tool like minicom (or Putty) - either on the Raspberry Pi or attach the smart-meter to a computer and check if any serial data is incoming.

**Comment by mainzelM** [comment]
Hi raymar9

Thanks for your reply! In the meantime the EKZ support team has contacted me: my smartmeter needs a firmware update before I can access it. The update should arrive within the next two months.
