### ISSUE TITLE
'Invalid data type.' Some data got lost.

### ISSUE THREAD

**Issue by kafisatz** [scs/smartmeter-datacollector#55]
I have a LG E450 from Energie Uster.
Things worked perfectly fine until 8 May 2023.
Now I get an error. 
Any Idea what is happening? 

For more details see here (I also attach a log file there) 
https://www.gurux.fi/node/21077

**Comment by raymar9** [comment]
I just tried to parse a data sample from your log file using a unit test in our software (+debugger) and the DLMS translator from Gurux. Both failed. It seams that the meter in fact sends invalid data. It was a good idea that you posted it in the Gurux Forum since there are people who know the DLMS protocol very well.

Did you use the previous software version v1.0.x? However, I performed the test with the current version - without success, so an update would probably not improve the result.
